# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcluster.proto\x12\x07\x63luster\"\x10\n\x0e\x43lusterRequest\"?\n\x0f\x43lusterResponse\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12\x16\n\x0ekeyspace_count\x18\x02 \x01(\x05\x32U\n\x0e\x43lusterService\x12\x43\n\x0eGetClusterInfo\x12\x17.cluster.ClusterRequest\x1a\x18.cluster.ClusterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLUSTERREQUEST']._serialized_start=26
  _globals['_CLUSTERREQUEST']._serialized_end=42
  _globals['_CLUSTERRESPONSE']._serialized_start=44
  _globals['_CLUSTERRESPONSE']._serialized_end=107
  _globals['_CLUSTERSERVICE']._serialized_start=109
  _globals['_CLUSTERSERVICE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
