worker_processes auto;

events {
    worker_connections 2048;
}

# TCP
stream {

    upstream cassandra_cluster {
        # least_conn; # so it's round-robin by default
        server cass1:9042 max_fails=3 fail_timeout=30s;
        server cass2:9042 max_fails=3 fail_timeout=30s;
        server cass3:9042 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 9042;
        proxy_connect_timeout 10s;
        proxy_timeout 1h;
        proxy_pass cassandra_cluster;
    }
}

# HTTP
http {
    include       /etc/nginx/mime.types;
    default_type  text/plain;
    sendfile      on;
    keepalive_timeout 65;

    upstream api_backend {
        least_conn;  
        server service_a:8000 max_fails=3 fail_timeout=10s;
        server service_b:8000 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://api_backend;

            proxy_http_version 1.1;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 10s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }

        location /slow {
            proxy_pass http://api_backend;

            proxy_http_version 1.1;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 10s;
            proxy_send_timeout 120s;
            proxy_read_timeout 120s;
        }

        location /status {
            return 200 "OK: nginx reverse-proxy to service_a & service_b\n";
        }
    }

    server {
        listen 8081;

        location / {
            return 200 "OK: nginx is running\n";
        }
    }

    server {
        listen 8082;

        location / {
            return 200
"Cassandra TCP load balancer active.
Backends:
 - cass1:9042
 - cass2:9042
 - cass3:9042

Use:
  cqlsh localhost 9042
";
        }
    }
}
